title: Emil Klasan
email: emilklasan@gmail.com
description: >-
    Incredible guy, really
baseurl: "/"
url: "https://emilklasan.github.io"
github_username:  EmilKlasan
show_downloads: false

markdown: kramdown
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
